
$('body').append("<style type=\'text/css\'> ul, ol, li {margin:0;padding:0;list-style:none;} a {color:#373937;text-decoration:none;} i {font-style:normal;} .floatwindow_fd_conct img {border:none;max-width:100%;max-height:100%;} .floatwindow_fd_conct {position:fixed;z-index:9999999;top:30%;right:0px;cursor:pointer;transition:all .3s ease;font-size:14px;} .floatwindow_fd_img {width:40px;background:#fd3939;min-height:188px;} .floatwindow_fd_img img {position:absolute;top:50%;margin-top:-94px;} .floatwindow_suspend {display:flex;position:absolute;left:-40px;transition:right 0.6s ease-in-out;-o-transition:right 0.6s ease-in-out;-moz-transition:right 0.6s ease-in-out;-webkit-transition:right 0.6s ease-in-out;} .floatwindow_fd_main {min-height:188px;border-left:none;background:#fff;} .floatwindow_fd_main>div {min-height:178px;border:5px #fd3939 solid;} .floatwindow_fd_main ul {padding:14px 14px 14px 15px;} .floatwindow_fd_main li a {display:block;height:30px;color:#666;font-size:14px;} .floatwindow_fd_main li span {display:inline-block;line-height:30px;padding-left:30px;} .floatwindow_fd_main li {background-size:20px;background-repeat:no-repeat;background-position:0 50%;position:relative;} .floatwindow_fd_main li i {position:absolute;top:0;left:0;width:30px;display:flex;display:-webkit-flex;justify-content:center;align-items:center;height:30px;}@media(max-width:768px){.floatwindow_fd_conct{display:none}} </style> <div class=\'floatwindow_fd_conct\'> <div class=\'floatwindow_suspend\'> <div class=\'floatwindow_fd_img\'><img src= img/floating_window/01.png></div> <div class=\'floatwindow_fd_main\'> <div> <ul>  <li class='floatwindow_tel'><a href=+91 94289 66781><i><img src=img/floating_window/02.png></i></a></li> <li class='floatwindow_email'><a href='mailto:shivamdental@hotmail.com' title='shivamdental@hotmail.com' target='_blank' id='A_9'><i><img src=img/floating_window/03.png></i><span>jessicadiamondtools@foxmail.com</span></a></li>  <li class='floatwindow_wechat'><a href='https://api.whatsapp.com/send?phone=8613797779412' title='8613797779412' target='_blank' id='A_8'><i><img src='/images/FloatWindow/18/wechat.png'></i><span>8613797779412</span></a></li>  </ul> </div> </div> </div> </div>");
var $_width = $('.floatwindow_suspend').outerWidth();
$('.floatwindow_fd_conct').hover(function () { $('.floatwindow_suspend').stop().animate({ 'left': -$_width }, 500) }, function () { $('.floatwindow_suspend').stop().animate({ 'left': '-40px' }, 300) })





